# Render Blueprint
# Deploy backend to Render

services:
  - type: web
    name: my-skill-api
    env: node
    region: singapore
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: FRONTEND_URL
        value: https://my-skill-frontend.vercel.app
      - key: MONGO_URI
        value: mongodb+srv://vincentvrza_db_user:JSYost2ZS1WwNc3G@cluster0.vkxoezx.mongodb.net/?appName=Cluster0
      - key: JWT_SECRET
        value: my-skill-jwt-secret-2024-production
